---
- name: Ensure openssl is installed
  apt:
    name: "openssl"
    state: present

- name: Create node_exporter private dir
  file:
    path: "{{ node_exporter_private_path}}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0700

- name: Generate host private key
  command: openssl genrsa -out {{ node_exporter_ssl_key_path }} 4096 creates={{ node_exporter_ssl_key_path }}

- name: Set private key permissions
  file:
    path: "{{ node_exporter_ssl_key_path }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0700"

- name: Generate CSR request
  command: openssl req -new -sha256 -subj "{{ node_exporter_ssl_cert_subj }}" -key {{ node_exporter_ssl_key_path }} -out {{ node_exporter_ssl_csr_path }} creates={{ node_exporter_ssl_csr_path }}

- name: Set CSR permissions
  file:
    path: "{{ node_exporter_ssl_csr_path }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0700"

- name: write the root ca private key to temporary directory
  copy:
    content: "{{ vault_prometheus_root_ca_key }}"
    dest: "{{ node_exporter_private_path }}/root_ca.key"

- name: Set root ca key permissions
  file:
    path: "{{ node_exporter_private_path }}/root_ca.key"
    mode: "0700"

- name: write the root ca cert to temporary directory
  copy:
    content: "{{ vault_prometheus_root_ca_pem }}"
    dest: "{{ node_exporter_private_path }}/root_ca.pem"

- name: Set root ca cert permissions
  file:
    path: "{{ node_exporter_private_path }}/root_ca.pem"
    mode: "0700"

- name: Generate signed SSL certificate
  command: openssl x509 -req -sha256 -days 1024 -in {{ node_exporter_ssl_csr_path }} -CA "{{ node_exporter_private_path }}/root_ca.pem" -CAkey "{{ node_exporter_private_path }}/root_ca.key" -CAcreateserial -out {{ node_exporter_ssl_cert_path }} -extensions v3_ca creates={{ node_exporter_ssl_cert_path }}

- name: Set signed cert permissions
  file:
    path: "{{ node_exporter_ssl_cert_path }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0700"

# XXX there should be a way to delete this even if the previous steps fail
- name: Delete temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ node_exporter_private_path }}/root_ca.key"
    - "{{ node_exporter_private_path }}/root_ca.pem"
