---
- include: ansible-version.yml

- hosts: prometheus.infra.ooni.io
  become: false
  remote_user: root
  gather_facts: true
  pre_tasks:
    - name: bootstap python
      raw: if [ ! -x /usr/bin/python ]; then apt-get update && apt-get -y install python-simplejson python-apt; fi
      register: output
      changed_when: output.stdout != ""
  roles:
    - role: adm
      adm_passwd:
        - "{{ passwd.art }}"
        - "{{ passwd.darkk }}"
        - "{{ passwd.superq }}"

- hosts: prometheus.infra.ooni.io
  roles:
    - docker_py

- hosts: prometheus.infra.ooni.io
  gather_facts: false # already gathered
  vars:
    ansible_python_interpreter: "/root/venv/bin/python2.7"
    letsencrypt_nginx: yes
    letsencrypt_domains: "prometheus.infra.ooni.io"
    prometheus_listen_address: "127.0.0.1:8090"
    grafana_listen_address: "127.0.0.1:3001"
    prometheus_nginx: yes
  roles:
    - letsencrypt
    - alertmanager
    - prometheus
    - blackbox_exporter
    - grafana
